# (B4 corrected) module equality (g3-1)Λ = (g5-1)Λ  --  EXACT INTEGER test.
# In G_n = (Z/2^{n+2})^×/{±1} (cyclic of order 2^n, generated by both 3 and 5):
#   find t with 3 ≡ ±5^t (mod 2^{n+2});  then (g3-1) = (g5^t-1) = (g5-1)·ν,  ν = 1+ζ+...+ζ^{t-1}
#   in Z[G]/(1+σ^{2^{n-1}}) ≅ Z[ζ_{2^n}]  (σ ↦ ζ, ζ^{2^{n-1}} = -1).
#   Equality of modules  ⟺  ν is a unit  ⟺  det(mult-by-ν matrix) = ±1.   No floats anywhere.
for n in [3,4,5,6,7,8,9,10]:
    MOD=2**(n+2); N=2**n; d=2**(n-1)
    t=None
    for tt in range(N):
        if pow(5,tt,MOD) in (3%MOD, (-3)%MOD): t=tt; break
    assert t is not None
    # mult-by-ν matrix on Z[x]/(x^d+1), ν = 1+x+...+x^{t-1}
    R=PolynomialRing(ZZ,'x'); x=R.gen(); f=x**d+1
    nu=sum(x**i for i in range(t)) % f
    Mrows=[]
    for j in range(d):
        p=(x**j*nu)%f
        c=[ZZ(cc) for cc in p.list()]; Mrows.append(c+[0]*(d-len(c)))
    D=matrix(ZZ,Mrows).det()
    print("n=%-2d  t=%-4d (odd? %s)   det(mult_nu) = %s   unit? %s"
          % (n,t,t%2==1,D,abs(D)==1))
