# ROUND 0 - CAS arbitration of the bridge theorem, four claims:
#  (B1) eps_n := (X_n+1)/(X_n-1) = tan(3θ)/tan(θ),  θ=π/2^{n+2}      [triple-angle identity]
#  (B2) the KY-generator conjugates of η_n = tanθ carry a SIGN: g3^j(η) = (-1)^j tan(3^j θ)
#       -- verified by integrality of the alternating trace (and failure without signs)
#  (B3) hence eps_n = -η_n^{σ-1} (σ = g3); on log vectors λ(eps) = (σ-1)λ(η) exactly
#  (B4) module equality: (g3-1)·Z[G]·λ(η) = (g5-1)·Z[G]·λ(η)   [(ζ^t-1)/(ζ-1) unit, t odd]
import mpmath as mp
mp.mp.dps=40
def orbit(gen,n):
    MOD=2**(n+2); N=2**n
    return [pow(gen,i,MOD) for i in range(N)]
print("=== (B1) triple-angle identity ===")
for n in [2,3,5,7]:
    th=mp.pi/mp.mpf(2**(n+2)); X=2*mp.cos(2*th)
    lhs=(X+1)/(X-1); rhs=mp.tan(3*th)/mp.tan(th)
    print("  n=%d  |eps - tan3θ/tanθ| = %s" % (n, mp.nstr(abs(lhs-rhs),3)))
print("=== (B2) sign law: alternating trace integral, plain trace not ===")
for n in [2,3,4,5]:
    MOD=2**(n+2); N=2**n; th=mp.pi/MOD
    ks=orbit(3,n)
    alt=sum((-1)**j*mp.tan(mp.mpf(ks[j])*th) for j in range(N))
    pln=sum(mp.tan(mp.mpf(ks[j])*th) for j in range(N))
    print("  n=%d  Σ(-1)^j tan(3^j θ) = %-14s (int? %s)   Σ tan(3^j θ) = %-14s (int? %s)"
          % (n, mp.nstr(alt,10), abs(alt-mp.nint(alt))<mp.mpf('1e-25'),
             mp.nstr(pln,10), abs(pln-mp.nint(pln))<mp.mpf('1e-25')))
print("=== (B3) λ(eps) = (σ-1)λ(η) on the ⟨3⟩-orbit ===")
for n in [3,5,7]:
    MOD=2**(n+2); N=2**n; th=mp.pi/MOD
    ks=orbit(3,n)
    lam=[mp.log(abs(mp.tan(mp.mpf(k)*th))) for k in ks]          # λ_j = log|g3^j(η)|
    # λ(eps)_j = log|g3^j(eps)| ; eps conjugates from X-conjugates directly:
    lem=[]
    for j in range(N):
        Xj=2*mp.cos(2*mp.mpf(ks[j])*th)
        lem.append(mp.log(abs((Xj+1)/(Xj-1))))
    resid=max(abs(lem[j]-(lam[(j+1)%N]-lam[j])) for j in range(N))
    print("  n=%d  max|λ(eps)_j - (λ_{j+1}-λ_j)| = %s" % (n, mp.nstr(resid,3)))
print("=== (B4) module equality (g3-1)Λ = (g5-1)Λ  via integer HNF comparison ===")
for n in [3,4,5]:
    MOD=2**(n+2); N=2**n; d=2**(n-1); th=mp.pi/MOD; SC=10**9
    k5=orbit(5,n); lam5=[mp.log(abs(mp.tan(mp.mpf(k)*th))) for k in k5]
    k3=orbit(3,n); lam3=[mp.log(abs(mp.tan(mp.mpf(k)*th))) for k in k3]
    # lattice generated by shifts of (σ-1)λ in each parametrisation, embedded in R^N (⟨5⟩ order)
    # express the ⟨3⟩ vector in the ⟨5⟩ indexing: position of 3^j-orbit element within ⟨5⟩ list (mod ±)
    pos={}
    for i,k in enumerate(k5): pos[k]=i; pos[MOD-k]=i
    perm=[pos[k] for k in k3]
    A5=matrix(ZZ,[[int(mp.nint((lam5[(j+i+1)%N]-lam5[(j+i)%N])*SC)) for j in range(N)] for i in range(d)])
    rows3=[]
    for i in range(d):
        v=[0]*N
        for j in range(N):
            v[perm[(j)%N]] += 0
        # build (g3-1)λ shifted by g3^i, expressed in ⟨5⟩ coordinates:
        vec=[int(mp.nint((lam3[(j+i+1)%N]-lam3[(j+i)%N])*SC)) for j in range(N)]
        # coordinates currently in ⟨3⟩ ordering; re-express in ⟨5⟩ ordering:
        w=[0]*N
        for j in range(N): w[perm[j]]=vec[j]
        rows3.append(w)
    A3=matrix(ZZ,rows3)
    H5=A5.hermite_form(include_zero_rows=False); H3=A3.hermite_form(include_zero_rows=False)
    same=(H5.nrows()==H3.nrows()) and max(max(abs(H5[i,j]-H3[i,j]) for j in range(N)) for i in range(H5.nrows())) <= 2
    print("  n=%d  rank %d vs %d ; HNF agree within rounding (±2 units of 1e-9)? %s"
          % (n, H5.nrows(), H3.nrows(), same))
