#!/usr/bin/env python3
"""gen_blueprint_map.py - r14 (GPT r11 hw 190; r13: lem:barT; r14: CLAIMS_R14; r15: lem:oddtransfer / LEM_ODDTRANSFER (E15-1); r18: lem:normone, thm:rank3, lem:mo25). Generates docs/BLUEPRINT_MAP_1.0.2.md: one row per claim of
docs/CLAIMS_1.0.2.yaml with its paper location, Blueprint node(s), proof source (proofs/*.tex or \\leanok), Lean
declarations (checked to exist in lean/*.lean), certificate / log evidence (checked to exist). --check exits 1 on
any missing Lean declaration, missing evidence path, missing proof file or unknown Blueprint label."""
import yaml,re,os,sys
d=yaml.safe_load(open('docs/CLAIMS_1.0.2.yaml'))
bp=open('blueprint/src/content.tex').read()
env_re=re.compile(r'\\begin\{(theorem|lemma|proposition|corollary|definition)\}(\[[^\]]*(?:\{[^}]*\}[^\]]*)*\])?\\label\{([^}]+)\}(.*?)\\end\{\1\}',re.S)
proof_re=re.compile(r'\\begin\{proof\}(.*?)\\end\{proof\}',re.S)
nodes={}
for m in env_re.finditer(bp):
    nxt=env_re.search(bp,m.end()); tail=bp[m.end():nxt.start() if nxt else len(bp)]; pm=proof_re.search(tail)
    proof=pm.group(1) if pm else ''
    src=re.findall(r'\\input\{\\proofsdir/([^}]+)\}',proof)
    nodes[m.group(3)]=dict(title=(m.group(2) or '').strip('[]'),leanok='\\leanok' in proof or '\\leanok' in m.group(4),proof_src=('proofs/%s.tex'%src[0] if src else ('kernel (\\leanok)' if '\\leanok' in proof else ('' if not proof else 'inline'))))
MAP={'THM_A':['thm:A','thm:Acore','prop:F'],'LEM_A':['lem:A','lem:Aplus'],'LEM_B':['lem:B'],'LEM_C':['lem:C'],'LEM_D':['lem:D'],'LEM_E':['lem:E'],'LEM_EPRIME':['lem:Eprime'],'PROP_F':['prop:F'],
 'PROP_D_i':['lem:D0','prop:D'],'PROP_D_ii':['prop:D','lem:D1','lem:D2','lem:D3','lem:prod13'],'COR_APRIME':['cor:Aprime'],'COR_T':['cor:T'],'C7_ENCLOSURE':['lem:C7'],'C7_INTEGER':['lem:C7int'],'COR_7':['cor:7'],
 'THM_S0':['thm:S0','lem:Sgroup','lem:Sineq','lem:depthfloor','lem:oddtransfer'],'LEM_ODDTRANSFER':['lem:oddtransfer'],'COR_S1':['cor:S1','lem:Jt'],'THM_CERT':['thm:cert','thm:certcore','lem:barT','def:verifier'],'FAMILY_KY1000':['thm:family','lem:ky1000'],'KY1000_TARGET':['lem:ky1000target'],
 'FLAGSHIP_321':[],'CLASS1_E':['exp:class1'],'SVP_E':['exp:svp'],'LPROD_OBS':[],'CRT_CARRY':[],'LUO_GAP':[],'OLDNEW_LEMMA':['lem:oldnew'],
 'THM_SH':['thm:SH'],'COR_SHMOD':['cor:SHmod'],'COR_AHAT':['cor:Ahat','lem:ramare'],'COR_ORDER':['cor:order','lem:robbins'],'THM_P3':['thm:P3','def:p3','lem:horie13','lem:mo25-z3'],'COR_P3N4':['cor:P3n4'],'CERT_D3':['lem:D3cert'],'LEM_NORMONE':['lem:normone'],'THM_RANK3':['thm:rank3','lem:D3','lem:dirichlet']}
leansrc=''.join(open('lean/'+f).read() for f in os.listdir('lean') if f.endswith('.lean'))
bad=0; rows=[]
for c in d['claims']:
    labs=MAP.get(c['id'])
    if labs is None: print('UNMAPPED claim',c['id']); bad+=1; labs=[]
    for l in labs:
        if l not in nodes: print('UNKNOWN blueprint label',l,'for',c['id']); bad+=1
    decl_ok=[]
    for decl in c.get('lean',[]):
        short=decl.split('.')[-1]; ok=bool(re.search(r'\b(theorem|lemma|def)\s+'+re.escape(short)+r'\b',leansrc)); decl_ok.append((decl,ok)); bad+=not ok
    ev=[(e,os.path.exists(e)) for e in c.get('evidence',[])]; bad+=sum(1 for e,ok in ev if not ok)
    srcs=sorted({nodes[l]['proof_src'] for l in labs if l in nodes and nodes[l]['proof_src']})
    for s in srcs:
        if s.startswith('proofs/') and not os.path.exists(s): print('MISSING proof file',s); bad+=1
    rows.append('| %s | %s | %s | %s | %s | %s | %s |'%(c['id'],c.get('paper','-'),', '.join(labs) or '-',c['label'],'; '.join(srcs) or '-',
        '; '.join(('%s%s'%(x,'' if ok else ' (MISSING)')) for x,ok in decl_ok) or '-','; '.join(('%s%s'%(x,'' if ok else ' (MISSING)')) for x,ok in ev) or '-'))
out=['# BLUEPRINT_MAP_1.0.2 — paper / Blueprint / Lean / certificate correspondence (GENERATED by tools/gen_blueprint_map.py; do not edit)','',
     '| claim | paper | Blueprint node(s) | trust | proof source | Lean declarations | certificate / log |','|---|---|---|---|---|---|---|']+rows
out.append(''); out.append('Blueprint nodes: %d ; with proof source: %d ; kernel (\\leanok): %d. Every Blueprint node is listed in blueprint/src/content.tex; nodes not tied to a claim are literature inputs [L] or the setting.'%(len(nodes),sum(1 for n in nodes.values() if n['proof_src'] and n['proof_src']!='kernel (\\leanok)'),sum(1 for n in nodes.values() if n['leanok'])))
if '--check' in sys.argv:
    cur=open('docs/BLUEPRINT_MAP_1.0.2.md').read() if os.path.exists('docs/BLUEPRINT_MAP_1.0.2.md') else ''
    if cur!='\n'.join(out)+'\n': print('docs/BLUEPRINT_MAP_1.0.2.md is not the regenerated file'); bad+=1
    print('BLUEPRINT MAP CHECK: %s (claims %d, missing %d)'%('PASS' if not bad else 'FAIL',len(rows),bad)); sys.exit(1 if bad else 0)
open('docs/BLUEPRINT_MAP_1.0.2.md','w').write('\n'.join(out)+'\n'); print('wrote docs/BLUEPRINT_MAP_1.0.2.md rows',len(rows),'problems',bad)
