#!/usr/bin/env python3
"""gen_novelty_matrix.py (r20; LETTER_R18/R19 question (10), answered by default after two silences: tracker hw 1053; the reading
itself is hw 868-876, OPEN). Generates docs/NOVELTY_MATRIX.md from docs/CLAIMS_R<ver>.yaml: for each headline result of the two towers,
its claim id, paper location, trust label, the literature inputs it rests on (from the claims), the prior bound it is MEASURED AGAINST
(the comparator column below -- a fixed table in this generator, NOT a novelty verdict) and the novelty-reading status, which is the
author's OPEN item and is never filled in here. --check re-renders and compares byte-for-byte. No run-time path or timestamp is embedded."""
import sys,re,yaml
def cffver():
    m=re.search(r'^version: "?([A-Za-z0-9.]+)"?$',open('CITATION.cff',encoding='utf-8').read(),re.M); return m.group(1)
VER=cffver(); CLAIMS='docs/CLAIMS_%s.yaml'%VER.upper(); OUT='docs/NOVELTY_MATRIX.md'
# (tower, claim id, comparator = the prior statement the result is measured against, as cited in the paper)
ROWS=[('Z_2','THM_SH','none (abstract carrier / floor / lattice bound; no equivalent abstract statement was found in the sources read at Phase -1 -- the reading must decide)'),
      ('Z_2','THM_A','MO2016 Thm A (uniform in n, G(2,s,f)); KY Prop 4.1 (conditional on KY Conj 2.2); Horie-Horie 2009 thresholds'),
      ('Z_2','COR_AHAT','MO2016 Thm A (computation-free, every layer)'),
      ('Z_2','COR_ORDER','MO2016 Thm A; FK3 / MO2016 Cor B (l < 1e9)'),
      ('Z_2','COR_7','MO2016 G(2,6,1) < 7.8e12, G(2,6,2) < 2.8e6 (the printed values); Table 3 of the paper'),
      ('Z_2','THM_S0','KY Prop 4.1 (depth-2 refinement, conditional there); no published unconditional depth-t transfer known to us'),
      ('Z_2','FAMILY_KY1000','KY Table (the same 1000 primes excluded conditionally on KY Conj 2.2)'),
      ('Z_3','LEM_NORMONE','MO2013 sect 1 (the Horie unit eta_n); relative norm 1 and the transfer to the saturation root: not found in MO2013 / MO2016 in this form'),
      ('Z_3','THM_RANK3','MO2013 / MO2016 (rank of the log-lattice of eta_n is not computed there; spectral rank and exact covolume: not found)'),
      ('Z_3','THM_P3','MO2016 Thm A at p = 3 (uniform in n, G(3,s,f)); MO2013 Thm 0.3 / G_1(3,r,f)'),
      ('Z_3','COR_P3N4','MO2016 Thm A: G(3,4,1) = 3.7111e37, G(3,4,2) = 6.0919e18 (the paper: 1.0728e33 / 3.2753e16)')]
def render():
    d=yaml.safe_load(open(CLAIMS,encoding='utf-8')); by={c['id']:c for c in d['claims']}
    L=['# NOVELTY_MATRIX — what each headline result rests on and what it is measured against (GENERATED by tools/gen_novelty_matrix.py from the claims; do not edit)','',
       'Purpose: the container for the novelty reading (tracker hw 868-876, OPEN, the author\'s item). The comparator column names the prior',
       'bound each result is MEASURED AGAINST in the paper (Tables 1-2 and the text); it is not a novelty verdict. The last column is filled',
       'only by the author, after the reading; "OPEN" means no claim of novelty is made here. Inputs are the literature inputs of the claims',
       'ledger (tags: [used] / [historical] / [unread], TRUST.md).','',
       '| tower | claim | paper | label | rests on (L inputs) | measured against | novelty reading |','|---|---|---|---|---|---|---|']
    for tower,cid,comp in ROWS:
        c=by[cid]; ins='; '.join(c.get('inputs',[])) or 'none (F / C / M only)'
        L.append('| %s | %s | %s | %s | %s | %s | OPEN (hw 868-876) |'%(tower,cid,c.get('paper','').replace('|','/'),c.get('label','').replace('|','/'),ins.replace('|','/'),comp))
    L+=['','Rows: %d (Z_2 %d, Z_3 %d). Generated from %s.'%(len(ROWS),sum(t=='Z_2' for t,_,_ in ROWS),sum(t=='Z_3' for t,_,_ in ROWS),CLAIMS)]
    return '\n'.join(L)+'\n'
txt=render()
if '--check' in sys.argv:
    cur=open(OUT,encoding='utf-8').read() if __import__('os').path.exists(OUT) else ''
    ok=(cur==txt); print('NOVELTY MATRIX CHECK: %s (rows %d)'%('PASS' if ok else 'FAIL (stale; re-run tools/gen_novelty_matrix.py)',len(ROWS))); sys.exit(0 if ok else 1)
open(OUT,'w',encoding='utf-8').write(txt); print('wrote %s rows %d'%(OUT,len(ROWS)))
