#!/usr/bin/env python3
"""gen_p3_negctl_ledger.py (r19) -- the p = 3 read-only replay's negative-control ledger, generated from ONE JSON (GPT r18 items 25-26
= hw 901-902). Single source: sage/r19_trackB/p3_negctl_ledger_r19.json, written by scripts/verify_p3_readonly.sage --negctl at the
sealed run (structured: planted, rejected, per-control verdict and first reason, verifier/cert sha256). This tool renders it as
docs/P3_NEGCTL_LEDGER_R19.md and, with --check, re-renders and compares; it also requires planted == rejected and that the
structured summary sage/r19_trackB/p3_readonly_summary_r19.json agrees (negctl.planted/rejected, status PASS, containment
failed 0). No count is typed by hand anywhere: tools/check_constant_sync.py reads the count from the SAME JSON."""
import json, sys, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); os.chdir(ROOT)
SRC = os.environ.get('P3_NEGCTL_JSON', 'sage/r19_trackB/p3_negctl_ledger_r19.json')
SUM = os.environ.get('P3_SUMMARY_JSON', 'sage/r19_trackB/p3_readonly_summary_r19.json')
OUT = 'docs/P3_NEGCTL_LEDGER_R19.md'
J = json.load(open(SRC)); S = json.load(open(SUM))
bad = []
if J.get('format_version') != 'p3_negctl_ledger_r19': bad.append('ledger format_version')
if J['planted'] != J['rejected']: bad.append('planted %d != rejected %d' % (J['planted'], J['rejected']))
if len(J['controls']) != J['planted']: bad.append('control list length')
if any(not c['rejected'] for c in J['controls']): bad.append('a control was accepted')
if S.get('status') != 'PASS' or S.get('containment_failed') != 0 or (S.get('negctl') or {}).get('planted') != J['planted'] or (S.get('negctl') or {}).get('rejected') != J['rejected']:
    bad.append('summary JSON disagrees with the ledger (status %s, containment_failed %s, negctl %s)' % (S.get('status'), S.get('containment_failed'), S.get('negctl')))
if S.get('verifier_sha256') != J.get('verifier_sha256') or S.get('cert_sha256') != J.get('cert_sha256'): bad.append('summary/ledger sha256 differ')
def render():
    L = ['# P3 read-only replay -- negative-control ledger (r19; GENERATED by tools/gen_p3_negctl_ledger.py from the replay JSON shipped as sage/r19_trackB/p3_negctl_ledger_r19.json -- do not edit; the fresh JSON of every verifier run must render this same file)', '',
         'Verifier scripts/verify_p3_readonly.sage sha256 `%s` ; certificate sha256 `%s` ; planted %d ; rejected %d ; containment on the shipped certificate %d/%d.' % (
             J['verifier_sha256'], J['cert_sha256'], J['planted'], J['rejected'], S['containment_checked'] - S['containment_failed'], S['containment_checked']), '',
         'Controls 1-5 are the r18 planted set (kept); 6-12 are the r19 set (GPT r18 items 17-23): each MEETS the recomputed interval but does not CONTAIN it, so the r18 overlap gate would have accepted it (evidence for control 6: sage/r19_trackB/r18gate_accepts_plant6_r19.log).', '',
         '| # | planted certificate | verdict | first reason | containment failed/checked |', '|---|---|---|---|---|']
    for c in J['controls']:
        L.append('| %d | %s | %s | %s | %d/%d |' % (c['id'], c['description'].replace('|', '/'), 'REJECTED' if c['rejected'] else 'ACCEPTED (WRONG)', c['first_reason'].replace('|', '/')[:120], c['containment_failed'], c['containment_checked']))
    return '\n'.join(L) + '\n'
txt = render()
if '--check' in sys.argv:
    if not os.path.exists(OUT): bad.append('ledger md missing')
    elif open(OUT).read() != txt: bad.append('docs/P3_NEGCTL_LEDGER_R19.md is stale (re-run tools/gen_p3_negctl_ledger.py)')
    print('P3 NEGCTL LEDGER: %s (planted %d, rejected %d, source %s)' % ('PASS' if not bad else 'FAIL', J['planted'], J['rejected'], SRC))
    for b in bad: print('  FAIL:', b)
    sys.exit(1 if bad else 0)
if bad:
    print('P3 NEGCTL LEDGER: refusing to render, source inconsistent:', bad); sys.exit(1)
open(OUT, 'w').write(txt); print('wrote', OUT, 'planted', J['planted'], 'rejected', J['rejected'])
