#!/usr/bin/env python3
"""gen_manifest.py - generate / check MANIFEST_SHA256.txt for the weber_general_n package (r11).

  python3 tools/gen_manifest.py            -> (re)write MANIFEST_SHA256.txt at the package root
  python3 tools/gen_manifest.py --check    -> verify every listed file; exit 0 iff all match and
                                              no covered file is missing from the manifest

Coverage (GPT r10 hw 57-60, 70): every regular file under the package root EXCEPT
  - MANIFEST_SHA256.txt itself and the superseded r8 manifest under certificates/superseded/
  - HANDOFF.md (records the zip hash AFTER sealing, so it cannot be inside the manifest)
  - anything containing '.bak' in its name, editor/OS droppings (.DS_Store), *.pyc, __pycache__
  - verify_out/ (outputs of scripts/verify_all_portable.sh; produced, not shipped as claims)
  - paper/draft/*.aux *.log *.out *.toc *.bbl *.blg *.synctex.gz (LaTeX by-products)
  - *.sage.py anywhere (Sage preparse by-products; path-dependent, regenerated by every run; r18)
  - .git/
Pure python3 (hashlib); no md5, no shasum, no absolute paths.
"""
import os, sys, hashlib
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
MAN = os.path.join(ROOT, 'MANIFEST_SHA256.txt')
SKIP_DIRS = {'.git', '__pycache__', 'verify_out'}
SKIP_SUFF = ('.aux', '.log', '.out', '.toc', '.bbl', '.blg', '.synctex.gz', '.pyc', '.fls', '.fdb_latexmk')
SKIP_NAMES = {'MANIFEST_SHA256.txt', 'HANDOFF.md', '.DS_Store'}

def covered(rel):
    parts = rel.split('/')
    if any(p in SKIP_DIRS for p in parts[:-1]): return False
    name = parts[-1]
    if name in SKIP_NAMES or '.bak' in name: return False
    if name.endswith('.sage.py'): return False   # r18: Sage preparse by-product; its header embeds the ABSOLUTE path of the .sage source, so it is regenerated differently on every checkout (caught by the staging seal, E18-1)
    if rel.startswith('paper/draft/') and name.endswith(SKIP_SUFF): return False
    if rel == 'certificates/superseded/manifest_r8.sha256': return False
    return True

def walk():
    out = []
    for dp, dns, fns in os.walk(ROOT):
        dns[:] = sorted(d for d in dns if d not in SKIP_DIRS)
        for fn in sorted(fns):
            rel = os.path.relpath(os.path.join(dp, fn), ROOT).replace(os.sep, '/')
            if covered(rel): out.append(rel)
    return out

def sha(rel):
    h = hashlib.sha256()
    with open(os.path.join(ROOT, rel), 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''): h.update(chunk)
    return h.hexdigest()

if '--check' in sys.argv:
    if not os.path.exists(MAN): print('MANIFEST_SHA256.txt missing'); sys.exit(1)
    listed = {}
    for line in open(MAN):
        line = line.rstrip('\n')
        if not line or line.startswith('#'): continue
        h, rel = line.split('  ', 1); listed[rel] = h
    bad = 0
    for rel, h in listed.items():
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p): print('MISSING  %s' % rel); bad += 1
        elif sha(rel) != h: print('MISMATCH %s' % rel); bad += 1
    extra = [r for r in walk() if r not in listed]
    for r in extra: print('UNLISTED %s' % r)
    print('manifest: %d listed, %d failed, %d unlisted' % (len(listed), bad, len(extra)))
    sys.exit(0 if (bad == 0 and not extra) else 1)
else:
    files = walk()
    with open(MAN, 'w') as f:
        f.write('# MANIFEST_SHA256.txt - weber_general_n r11 ; generated by tools/gen_manifest.py ; %d files\n' % len(files))
        f.write('# check: python3 tools/gen_manifest.py --check   (or: sha256sum -c after stripping the # lines)\n')
        for rel in files: f.write('%s  %s\n' % (sha(rel), rel))
    print('MANIFEST_SHA256.txt written: %d files' % len(files))
